# =====================================================
# Configuración de la API REST api-productos
# =====================================================

# Puerto del servidor embebido Tomcat
server.port=8080

# Log DEBUG para nuestro paquete
logging.level.com.universidad=DEBUG
logging.pattern.console=%d{HH:mm:ss} %-5level %logger{36} - %msg%n